### ISSUE TITLE
Fork Scraper

### ISSUE THREAD

**Issue by PlashSpeed-Aiman** [iqfareez/iium_schedule#1]
If you want a working scraper, you can port my Java code to dart. It can collect the course data correctly

**Comment by iqfareez** [comment]
@PlashSpeed-Aiman Hi just wanna update that I (alhamdulillah) successfully ported your code to Dart.

Made a quick integration with the app. So far so good, only had a minor issue here and there.

https://user-images.githubusercontent.com/60868965/141406022-bc7799dc-9ec1-4b85-965b-2221ee32733c.mp4

Can try with the [apk](https://github.com/iqfareez/flutter_iium_schedule/releases/tag/1.0.0-pre.1%2B1) if you want

And also, I published the scrapper implementation to the pub.dev:
https://pub.dev/packages/albiruni

Thanks haha & salam jumaat.

**Comment by PlashSpeed-Aiman** [comment]
Looks good, the UI is just amazing. Much better implemented than mine. I can see why it's much easier to make beautiful UI with Flutter.

**Comment by iqfareez** [comment]
Thank you 😄
