### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by PlashSpeed-Aiman** [iqfareez/iium_schedule#6]
![image](https://user-images.githubusercontent.com/62431177/156244189-9658fa70-0e0c-4014-80e9-c6add460bca0.png)

**Comment by iqfareez** [comment]
Thanks! Almost forgot about that.

**Comment by iqfareez** [comment]
All documentation will be added to **https://iiumschedule.vercel.app/**

To extract JSON: https://iiumschedule.vercel.app/docs/extract/imaluum

**Comment by iqfareez** [comment]
Done
